// This file is auto-generated by ./bin/rails stimulus:manifest:update
// Run that command whenever you add a new controller or create them with
// ./bin/rails generate stimulus controllerName

import { application } from "./application"

import AddressAutocompleteController from "./address_autocomplete_controller"
application.register("address-autocomplete", AddressAutocompleteController)

import ChatroomSubscriptionController from "./chatroom_subscription_controller"
application.register("chatroom-subscription", ChatroomSubscriptionController)

import EventController from "./event_controller"
application.register("event", EventController)

import GenreController from "./genre_controller"
application.register("genre", GenreController)

import HelloController from "./hello_controller"
application.register("hello", HelloController)

import HideStuffController from "./hide_stuff_controller"
application.register("hide-stuff", HideStuffController)

import MapController from "./map_controller"
application.register("map", MapController)

import TabsController from "./tabs_controller"
application.register("tabs", TabsController)

import ToggleController from "./toggle_controller"
application.register("toggle", ToggleController)
